name: Run Tests and Generate Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]

jobs:
  test:
    name: Run Jest Tests and Update Coverage
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            smartspeech/frontend/package-lock.json
            

      # Install dependencies
      - name: Install dependencies
        working-directory: smartspeech/frontend
        run: npm ci
        

      # Run Jest tests with coverage enabled
      - name: Run tests with coverage
        working-directory: smartspeech/frontend
        run: npm test -- --coverage --watchAll=false

      # Move the coverage report into the Docusaurus static folder
      - name: Copy coverage report to Docusaurus static folder
        run: |
          mkdir -p docs/static/coverage
          cp -r smartspeech/frontend/coverage/lcov-report/* docs/static/coverage/
      
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage-report
          path: smartspeech/frontend/coverage/lcov-report